const words1 = [
	new Word(["a kid", "kid"], "ребенок"),
	new Word(["to park", "park"], "припарковать машину"),
	new Word("soft-hearted", "мягкий, отзывчивый, добрый"),
	new Word("top", "вершина"),
	new Word(["to mind", "mind"], "возражать"),
	new Word(["to fix", "fix"], "чинить"),
	new Word("dumb", "Немой, глупый"),
	new Word("smart", "Красивый, Умный"),
	new Word("advanced", "продвинутый"),
	new Word("terrific", "потрясающий"),
	new Word(["to showoff", "showoff"], "рисоваться, выставлять на показ"),
	new Word(["to care", "care"], "заботиться, волноваться"),
	new Word("jealous", "ревнивый"),
	new Word(["to cheat", "cheat"], "жульничать"),
	new Word("cheat sheet", "шпаргалка"),
	new Word("flavour", "вкус"),
	new Word("rotten", "Гнилой"),
	new Word("silly", "глупый"),
	new Word("harm", "вред"),
	new Word(["to creep", "creep"], "красться"),
];
const words2 = [
	new Word("witchcraft", "черная магия, колдовство"),
	new Word("philosopher", "философ"),
	new Word("caretaker", "смотритель"),
	new Word("legendary", "легендарный"),
	new Word("concentrate on", "сосредоточиться на"),
	new Word("surroundings", "местность, окружение"),
	new Word(["a dormitory", "dormitory"], "спальня (в интернате)"),
	new Word(["a wizard", "wizard"], "волшебник, кудесник"),
	new Word("wizardry", "волшебство, чары"),
	new Word(["to enroll", "enroll"], "зачислять(ся), записать(ся)"),
	new Word(["to enroll at a college", "to enroll at college", "enroll at a college", "enroll at college"], "быть зачисленным в колледж", false),
	new Word(["to enroll on a course", "to enroll on course", "enroll on a course", "enroll on course"], "быть зачисленным в колледж", false),
	new Word(["to be enrolled at a university", "to be enrolled at university", "be enrolled at a university", "be enrolled at university"], "быть зачисленным в университет", false),
	new Word(["a queue", "queue"], "очередь"),
	new Word(["a long queue", "long queue"], "длинная очередь", false),
	new Word(["to join the queue", "join the queue", "to join queue", "join queue"], "присоединиться к очереди", false),
	new Word(["to be in the queue", "be in the queue", "to be in queue", "be in queue"], "быть в очереди", false),
	new Word(["to jump the queue", "jump the queue", "to jump queue", "jump queue"], "пройти, пролезть без очереди", false),
	new Word(["a queue jumper", "queue jumper"], "человек, проходящий без очереди"),
	new Word(["a line", "line"], "очередь (Ам.)"),
	new Word(["to queue (queued, queueing/queuing)", "to queue", "queue"], "стоять в очереди"),
	new Word(["to queue for (the bus)", "to queue for", "queue for", "to queue for the bus", "queue for the bus", "to queue for bus", "queue for bus"], "стоять в очереди за чем-то", false),
	new Word(["to vanish", "vanish"], "исчезать"),
	new Word(["to vanish from sight", "vanish from sight"], "исчезнуть из виду", false),
	new Word("vanishing species", "исчезающие виды", false),
	new Word(["to tickle ", "tickle"], "щекотать"),
	new Word("solid", "1. твердый, плотный \n 2. однородный, сплошной"),
	new Word(["a solid wall", "solid wall"], "твердая стена", false),
	new Word("solid gold", "полностью из золота"),
	new Word("solid advice", "надежный совет"),
	new Word(["to force", "force"], "принуждать, заставлять"),
	new Word(["to force on (upon) someone", "force on (upon) someone",
		"to force on someone", "force on someone",
		"to force upon someone", "force upon someone"], "навязать что-либо кому-то", false),
	new Word(["to force smb to do smth", "force smb to do smth", "to force smb do smth", "force smb do smth"], "заставить кого-то что-либо делать", false),
	new Word(["to force a door", "force a door", "to force door", "force door"], "толкнуть дверь", false),
	new Word("force", "сила"),
	new Word("by force", "силой", false),
	new Word("from force of habit", "в силу привычки", false),
	new Word(["to squeak", "squeak"], "пищать, скрипеть"),
	new Word(["a squeak", "squeak"], "писк, скрип"),
	new Word("squeaky", "писклявый, скрипучий"),
	new Word(["a mess", "mess"], "беспорядок"),
	new Word(["to be (in) a mess", "be (in) a mess", "to be (in) mess", "be (in) mess",
		"to be a mess", "be a mess", "to be mess", "be mess",
		"to be in a mess", "be in a mess", "to be in mess", "be in mess"], "быть в беспорядке", false),
	new Word("messy", "неубранный, неряшливый, грязный"),
	new Word(["to mess", "mess"], "запачкать"),
	new Word(["to mess about (around)", "mess about (around)",
		"to mess about", "mess about",
		"to mess around", "mess around"], "играть (шалить)", false),
	new Word(["to mess up", "mess up"], "пачкать, портить", false),
	new Word("complicated", "сложный"),
	new Word("rare", "редкий"),
	new Word("rarely", "редко"),
	new Word(["to relieve", "relieve"], "облегчать"),
	new Word(["to relieve pain", "relieve pain"], "облегчить боль", false),
	new Word(["to relieve trouble", "relieve trouble"], "решить проблемы", false),
	new Word(["to be relieved", "be relieved"], "чувствовать облегчение", false),
	new Word(["to relieve a headache", "relieve a headache", "to relieve headache", "relieve headache"], "избавить(ся) от головной боли", false),
	new Word("relief", "облегчение"),
	new Word("with relief", "с облегчением", false),
	new Word(["a sigh of relief", "sigh of relief"], "вздох облегчения", false),
	new Word(["a sense of relief", "sense of relief"], "чувство облегчения", false),
	new Word(["to one's relief", "one's relief"], "к чьему-то облегчению", false),
	new Word(["to drone", "drone"], "жужжать, гудеть"),
	new Word(["to drone on", "drone on"], "бубнить", false),
	new Word("droning", "гудящий, жужжащий"),
	new Word(["to warn", "warn"], "предупреждать"),
	new Word(["to warn sb about(/of) smth", "warn sb about(/of) smth",
		"to warn sb about smth", "warn sb about smth",
		"to warn sb of smth", "warn sb of smth",
		"to warn sb about(of) smth", "warn sb about(of) smth",
		"to warn sb about/of) smth", "warn sb about/of smth"], "предупредить о чем-то", false),
	new Word(["to warn against sth(/smb)", "warn against sth(/smb)",
		"to warn against sth", "warn against sth",
		"to warn against smb", "warn against smb",
		"to warn against sth(smb)", "warn against sth(smb)",
		"to warn against sth/smb", "warn against sth/smb"], "предостеречь", false),
	new Word(["a warning", "warning"], "предупреждение"),
];
const words3 = [
	new Word("firmly", "твердо"),
	new Word("downwards", "вниз"),
	new Word("eccentric", "эксцентричный"),
	new Word("worth", "стоящий"),
	new Word(["to be worth doing smth", "be worth doing smth"], "стоит сделать что-либо", false),
	new Word("outfit", "наряд"),
	new Word("fancy dress", "нарядное платье"),
	new Word("fancy-dress", "нарядный, маскарадный"),
	new Word(["a fancy-dress party", "fancy-dress party"], "костюмированная вечеринка", false),
	new Word("immense", "огромный, громадный"),
	new Word("reluctant", "неохотный"),
	new Word("reluctance", "нежелание"),
	new Word(["to attach", "attach"], "прикреплять"),
	new Word(["to attach smth to smth", "attach smth to smth"], "прикреплять что-то к чему-то", false),
	new Word("attached", "прикрепленный"),
	new Word(["to be attached to smth", "be attached to smth"], "быть прикрепленным к чему-то", false),
	new Word(["to detach", "detach"], "отделять"),
	new Word(["to detach smth from smth", "detach smth from smth"], "отделять что-то от чего-то", false),
	new Word("detachable", "съемный, отделяемый"),
	new Word("detached", "беспристрастный, равнодушный"),
	new Word(["a detached house", "detached house"], "отдельный дом", false),
	new Word(["to tie", "tie"], "привязывать, завязывать"),
	new Word(["to tie smth to smth", "tie smth to smth"], "привязывать что-то к чему-то", false),
	new Word(["to tie smth round smth", "tie smth round smth"], "завязывать что-то вокруг чего-то", false),
	new Word(["to tie a knot", "tie a knot", "to tie knot", "tie knot"], "завязывать узел", false),
	new Word(["to tie a bow", "tie a bow", "to tie bow", "tie bow"], "завязывать бант", false),
	new Word(["to tie shoelaces", "tie shoelaces"], "завязывать шнурки", false),
	new Word(["to tie a hair ribbon", "tie a hair ribbon", "to tie hair ribbon", "tie hair ribbon"], "завязывать ленту", false),
	new Word(["to be tied with string(/rope)", "be tied with string(/rope)",
		"to be tied with string", "be tied with string",
		"to be tied with rope", "be tied with rope"], "быть связанным веревкой", false),
	new Word(["a tie", "tie"], "галстук"),
	new Word(["a bow tie", "bow tie"], "галстук-бабочка", false),
	new Word("starch", "крахмал"),
	new Word(["to starch", "starch"], "крахмалить"),
	new Word("starched", "накрахмаленный"),
	new Word("stiff", "онемевший, оцепеневший, жесткий"),
	new Word(["to chew", "chew"], "жевать"),
	new Word("ridiculous", "смешной, нелепый"),
	new Word(["to flap", "flap"], "1. Хлопать, шлепать; 2. развеваться"),
	new Word("funeral", "похороны"),
	new Word(["to hold a funeral", "hold a funeral", "to hold funeral", "hold funeral"], "проводить похороны", false),
	new Word("dignity", "достоинство"),
	new Word(["beneath one’s dignity", "beneath ones dignity"], "ниже чьего-то достоинства", false),
	new Word(["to keep one’s dignity", "keep one’s dignity", "to keep ones dignity", "keep ones dignity"], "сохранить достоинство", false),
	new Word(["to lose one’s dignity", "lose one’s dignity", "to lose ones dignity", "lose ones dignity"], "потерять достоинство", false),
	new Word(["to stand on one’s dignity", "stand on one’s dignity", "to stand on ones dignity", "stand on ones dignity"], "держаться с большим достоинством", false),
	new Word("dignified", "полный достоинства, величавый"),
];
const words4 = [
	new Word(["an individual", "individual"], "личность, индивидуум"),
	new Word(["a robot", "robot"], "робот"),
	new Word("kleptomania", "клептомания"),
	new Word("intellect", "ум, разум, интеллект"),
	new Word("in combination", "в сочетании, в комбинации"),
	new Word("combined", "совместный, объединенный", false),
	new Word(["a hybrid", "hybrid"], "гибрид"),
	new Word("sterilized", "простерилизованный"),
	new Word(["to imitate", "imitate"], "имитировать"),
	new Word("potential", "потенциальный"),
	new Word("emotional", "эмоциональный"),
	new Word(["to express", "express"], "выражать"),
	new Word(["to express thanks", "express thanks"], "выразить благодарность", false),
	new Word("nerve", "1. Нерв; 2. Смелость"),
	new Word(["to suffer from nerves", "suffer from nerves"], "страдать от нервов", false),
	new Word(["to get on one’s nerves", "get on one’s nerves",
		"to get on ones nerves", "get on ones nerves"], "действовать кому-то на нервы", false),
	new Word(["to have the nerve to do smth", "have the nerve to do smth",
		"to have nerve to do smth", "have nerve to do smth"], "иметь смелость (решительность) что-то сделать", false),
	new Word("nervous", "нервный"),
	new Word(["to bother smb with(/about) smth", "bother smb with(/about) smth",
		"to bother smb with smth", "bother smb with smth",
		"to bother smb about smth", "bother smb about smth"], "беспокоить кого-то чем-то", false),
	new Word("indifferent", "равнодушный"),
	new Word("indifferently", "равнодушно", false),
	new Word("beside", "рядом"),
	new Word("besides", "кроме того"),
	new Word(["to require smth", "require smth"], "требовать что-то"),
	new Word("equipment", "снаряжение, экипировка, оборудование"),
	new Word(["to supply", "supply"], "снабжать"),
	new Word(["to supply smb with smth", "supply smb with smth"], "снабжать кого-то чем-то"),
	new Word(["to supply smth to smb/smth", "supply smth to smb/smth"], "поставлять что-тому кому-то/чему-то"),
	new Word(["a supply", "supply"], "запас", false),
	new Word("irritable", "раздражительный"),
	new Word("irritably", "раздраженно", false),
	new Word(["a case", "case"], "случай"),
	new Word(["to work on the case", "work on the case",
		"to work on case", "work on case"], "работать над каким-то случаем", false),
	new Word("in case", "в случае", false),
	new Word("in any case", "в любом случае", false),
	new Word("just in case", "на всякий случай", false),
	new Word("in that case", "в этом случае", false),
	new Word("worn out", "поношенный"),
	new Word(["a record", "record"], "рекорд, запись"),
	new Word(["to set a record", "set a record",
		"to set record", "set record"], "установить рекорд", false),
	new Word(["to break the record", "break the record", "to break record", "break record"], "побить рекорд", false),
	new Word(["to hold the record", "hold the record", "to hold record", "hold record"], "удержать рекорд", false),
	new Word(["to predict", "predict"], "предсказывать"),
	new Word(["to insist on smth", "insist on smth"], "настаивать на чем-то"),
	new Word(["a desire", "desire"], "желание"),
	new Word(["a variety", "variety"], "разнообразие"),
	new Word(["a variety of goods", "variety of goods"], "разнообразие товаров", false),
	new Word("various", "разнообразный", false),
	new Word(["an advantage", "advantage"], "преимущество"),
	new Word(["an advantage over smb", "advantage over smb"], "преимущество над кем-то", false),
	new Word(["to have the advantage of doing smth", "have the advantage of doing smth",
		"to have advantage of doing smth", "have advantage of doing smth"], "иметь преимущество", false),
	new Word(["to do smth to advantage", "do smth to advantage"], "делать что-то с пользой", false),
	new Word(["to take advantage of smth", "take advantage of smth"], "воспользоваться чем-либо", false),
	new Word(["a disadvantage", "disadvantage"], "недостаток", false),
]
// new Word(["", ""], ""),
// new Word("", ""),

const AllParts: Words[] = [
	{ words: words1, name: "Часть 1" },
	{ words: words2, name: "Часть 2" },
	{ words: words3, name: "Часть 3" },
	{ words: words4, name: "Часть 4" },
]

interface Words
{
	words: Word[],
	name: string,
}